### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by wang-morris** [wang-morris/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create a HTML skeleton for the webpage
- [x] Add a background for your car
- [x] create a div to store your car 
- [x]  Add a top-down image of a car
- [x] Ensure the page looks good on both mobile-sized and desktop-sized screens.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary
- [x] test all functionality again in a private browser
- [x] Fix all errors
