### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by wang-morris** [wang-morris/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create a main.js file
- [x] Create a simple _data model_ that includes which way the car is facing, (up, down, left, right).
- [x] listen for _'keydown'_ events on the _document_
- [x] define a function that makes car face either up, down, left, or right depending on which arrow key was hit
- [x] Clean up all unnecessary styling.
- [x] Test the app some more in a private browsing tab.
- [x] Fix all errors.
