### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by wang-morris** [wang-morris/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add a location to your data model to hold the car's x and y coordinates on the page.
- [x] Use absolute positioning for your image.
- [x] [Use the style property](https://developer.mozilla.org/en-US/docs/Web/API/ElementCSSInlineStyle/style) of element objects to change your car's top and left box offset styles.
- [x] add event listener for space bar
- [x] define a function that moves the car a few pixels every 16 milliseconds
- [x] Clean up all unnecessary styling.
- [x] Test the app some more in a private browsing tab.
- [x] Fix all errors.
