### ISSUE TITLE
User can stop their car

### ISSUE THREAD

**Issue by wang-morris** [wang-morris/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [ ] add boolean to data model indicating whether or not the car has started
- [ ] add another if statement for if the car is in motion
- [ ] stop the car if the user presses space again;
- [ ] Clean up all unnecessary styling.
- [ ] Test the app some more in a private browsing tab.
- [ ] Fix all errors.
